# Generated by Django 2.1 on 2019-05-27 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.TextField(max_length=100, verbose_name='Entity')),
                ('entity_type', models.CharField(choices=[('PERSON', 'PERSON'), ('NORP', 'NORP'), ('FAC', 'FAC'), ('ORG', 'ORG'), ('GPE', 'GPE'), ('LOC', 'LOC'), ('PRODUCT', 'PRODUCT'), ('EVENT', 'EVENT'), ('WORK_OF_ART', 'WORK_OF_ART'), ('LAW', 'LAW'), ('LANGUAGE', 'LANGUAGE'), ('DATE', 'DATE'), ('TIME', 'TIME'), ('PERCENT', 'PERCENT'), ('MONEY', 'MONEY'), ('QUANTITY', 'QUANTITY'), ('ORDINAL', 'ORDINAL'), ('CARDINAL', 'CARDINAL')], default='PERSON', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=1500, verbose_name='title')),
                ('description', models.TextField(max_length=10000, verbose_name='Description')),
                ('datestr', models.TextField(max_length=20, verbose_name='DateString')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='releventnews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities4thisnews', to='news.News'),
        ),
    ]
